---
title: "Seminar 4: oppgaver"
author: "Lise Rødland"
date: "April 6, 2021"
output:
  pdf_document: 
    keep_md: yes
  github_document: default
---
1. Last inn datasettet "VALGDATA.Rdata"
2. Hva er navnene på variablene i datasettet?
3. Hvor mange missing er det totalt i datasettet?
4. Hvor mange missing er det på hver enkelt variabel?
5. Lag et subset av dataene hvor du fjerner NA på variabelen valg.
6. Gjør variabelen kjønn til en kategorisk variabel der 1 = mann og 2 = kvinne.
7. Hvor mange kvinner og hvor mange menn er det i datasettet?
8. Finn gjennomsnittsalderen i datasettet.
9. Finn gjennomsnittsalderen til henholdsvis menn og kvinner. Regn ut forskjellen.
10. Få oversikt over variablen valg. Lag et plot som viser den univariate fordelingen, det vil si hvor mange har stemt på hvert av partiene?
11. Finn korrelasjonen mellom alder og rik.
12. Lag et spredningsdiagram mellom alder og rik med prediksjonslinje. Endre navnene på x-aksen, y-aksen, og gi diagrammet en tittel. 

## Variabler: 
* rik: Hvor viktig er det for deg å være rik, ha penger og dyre ting? Skalaen går fra 1 til 6 der 1 = veldig viktig og 6 = ikke viktig i det hele tatt. 
* alder: Alder i antall år
* kjonn: 1 = mann, 2 = kvinne
* tillit: Hvor stor tillit har du til politikere? Skalaen går fra 1 til 10 der 1 = ingen tillit og 10 = full tillit. 
* valg: Hvilket parti stemte du på ved forrige stortingsvalg? 
* redusere: Er du enig i at regjeringen skal omfordele goder? Skalaen går fra 1 til 5 der 1 = veldig enig og 5 = helt uenig.  